services:
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - UI_SERVER_PORT=${UI_SERVER_PORT}
      - API_SERVER_PORT=${API_SERVER_PORT}
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    depends_on:
      # - ui
      - api
    networks:
      fc-network:
  api:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api-container
    volumes: 
      - ./api/:/var/www/
      - ./docker/api/entrypoint.sh:/var/www/entrypoint.sh:ro
    ports:
      - "127.0.0.1:${API_SERVER_PORT}:${API_SERVER_PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      API_SERVER_PORT: ${API_SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      fc-network:
  # ui:
  #   container_name: ui-container
  #   build:
  #     context: .
  #     dockerfile: ./docker/ui/Dockerfile
  #     target: ${APP_ENV}
  #   ports:
  #     - 127.0.0.1:${UI_SERVER_PORT}:3000
  #   stdin_open: true
  #   tty: true
  #   volumes: 
  #     - ./ui:/app
  #     - node_modules:/app/node_modules
  #   depends_on:
  #     - api
  #   environment:
  #     - NODE_ENV=${APP_ENV}
  #   networks:
  #     fc-network:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      fc-network:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    ports:
      - "127.0.0.1:${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-container
    restart: always
    ports:
      - "${MONGODB_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_EXPRESS_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_EXPRESS_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb
networks:
  fc-network:
    driver: bridge
volumes:
    node_modules:
    redis_data:
    mongo-data: