name: Deploy Dockerized App

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Check for build-related changes on server
        id: check_changes
        run: |
          if ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "[[ -f /var/www/fc.io/deploy/last_deployed_commit ]]"; then
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
              cd /var/www/fc.io
              git fetch origin master
              LAST_DEPLOYED_COMMIT=\$(cat deploy/last_deployed_commit)

              if git diff --name-only "\$LAST_DEPLOYED_COMMIT" origin/master | grep -E '(docker-compose.yml|^docker/)'; then
                echo "true" > /tmp/build_required.txt
              else
                echo "false" > /tmp/build_required.txt
              fi
            EOF
          else
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'true' > /tmp/build_required.txt"
          fi

          BUILD_REQUIRED=$(ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cat /tmp/build_required.txt")
          echo "build_required=$BUILD_REQUIRED" >> $GITHUB_ENV

      - name: Deploy to server using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /var/www/fc.io
            git pull --rebase

            if [[ "${{ env.build_required }}" == "true" ]]; then
              echo "Build-related changes detected. Rebuilding containers."
              docker compose down
              docker compose up --build -d
            else
              echo "No build-related changes detected. Starting existing containers."
              docker compose up -d
            fi

            git rev-parse HEAD > deploy/last_deployed_commit
          EOF
